FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY frontend-requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r frontend-requirements.txt

COPY src/frontend ./src/frontend

EXPOSE 8501

CMD ["streamlit", "run", "src/frontend/app.py", "--server.address=0.0.0.0", "--server.port=8501"]